name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v3
        with:
          project_id: sfujiwara
          workload_identity_provider: projects/609385848802/locations/global/workloadIdentityPools/github-pool/providers/github-provider

      # - name: Login to GAR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: us-central1-docker.pkg.dev
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: make docker-build

      - name: Push Docker image
        run: make docker-push

      - name: Deploy to Cloud Run
        run: make cloud-run
